Repository CZERTAINLY/CZERTAINLY-IP-Discovery-Provider, pull requests merged in 2024-12, with the labels that each got.

#70 Fix handling transactions when discovering certificates with single thread
  src/main/java/com/czertainly/discovery/ip/service/impl/DiscoveryServiceImpl.java
Labels: bug, ignore-for-release

#71 Lower maximum for parallel executions
  src/main/java/com/czertainly/discovery/ip/service/impl/AttributeServiceImpl.java
Labels: enhancement, ignore-for-release

#72 Updates for release 1.6.0
  pom.xml
Labels: ignore-for-release

#73 Release 1.6.0
  pom.xml
  src/main/java/com/czertainly/discovery/ip/service/impl/AttributeServiceImpl.java
  src/main/java/com/czertainly/discovery/ip/service/impl/DiscoveryServiceImpl.java
  src/main/java/com/czertainly/discovery/ip/util/DiscoverIpHandler.java
Labels: ignore-for-release
